# Generated by Django 5.2.7 on 2025-10-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estudiante', models.CharField(max_length=150, verbose_name='Nombre del Estudiante')),
                ('identificacion', models.CharField(max_length=15, verbose_name='Identificación')),
                ('asignatura', models.CharField(max_length=100, verbose_name='Asignatura')),
                ('nota1', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nota 1')),
                ('nota2', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nota 2')),
                ('nota3', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nota 3')),
                ('promedio', models.DecimalField(decimal_places=2, editable=False, max_digits=5, verbose_name='Promedio')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'ordering': ['-promedio', 'nombre_estudiante'],
            },
        ),
    ]
